### ISSUE TITLE
Grammar failing with 0.15.3

### ISSUE THREAD

**Issue by brupelo** [tree-sitter/tree-sitter-agda#8]
Is this a bug?

    (py364_32) D:\mcve\tree-sitter-agda>tree-sitter --version
    tree-sitter 0.15.3 (4d4e4f3909358bb5abdc3c3de0640d1b4ff444fe)

    (py364_32) D:\mcve\tree-sitter-agda>rm -rf src

    (py364_32) D:\mcve\tree-sitter-agda>tree-sitter generate
    Unresolved conflict for symbol sequence:

      atom  •  'integer_token1'  …

    Possible interpretations:

      1:  (_atoms1  atom)  •  'integer_token1'  …
      2:  (lambda_clause_repeat1  atom)  •  'integer_token1'  …

    Possible resolutions:

      1:  Add a conflict for these rules: `_application`

**Comment by banacorn** [comment]
Issue reproduced, thanks for reporting this.

But I'll need to solve the CI failure first before coming back to this.

**Comment by banacorn** [comment]
I've rewritten the parser from scratch, now we're at `0.15.8`
